#!/usr/bin/env python3
"""
================================================================================
DQN FOR UAV TASK OFFLOADING - COMPLETE IMPLEMENTATION IN ONE FILE
================================================================================

Author: Educational Implementation for Reinforcement Learning Beginners
Purpose: Demonstrate DQN for binary task offloading in UAV-assisted edge computing

To run: python dqn_uav_offloading_complete.py

Dependencies: pip install numpy matplotlib

================================================================================
PROBLEM DESCRIPTION
================================================================================

In edge-enabled UAV (Unmanned Aerial Vehicle) networks:
- Ground devices (IoT sensors, mobile phones) generate computational tasks
- Each device has LIMITED computing power and battery
- UAVs fly overhead and offer POWERFUL edge computing services

THE DECISION: For each task, should the device:
  (A) Process LOCALLY? (slow, uses device battery)
  (B) OFFLOAD to UAV? (transmission cost, but faster processing)

GOAL: Minimize total DELAY + ENERGY consumption across all tasks

================================================================================
WHY REINFORCEMENT LEARNING?
================================================================================

The optimal decision depends on many factors:
- Task size and complexity
- Device's remaining energy
- Distance to nearest UAV
- Channel quality (wireless signal strength)

Traditional approaches require perfect knowledge and complex optimization.
RL ADVANTAGE: The agent LEARNS from experience and makes quick decisions!

================================================================================
DQN (Deep Q-Network) EXPLAINED
================================================================================

Q-Learning Basics:
- Q(s, a) = Expected future reward for taking action 'a' in state 's'
- If we knew Q for all (state, action) pairs, we'd always pick the best action!

The Problem:
- State space is continuous (infinite states possible)
- We can't store Q-values in a table

DQN Solution:
- Use a Neural Network to APPROXIMATE Q-values
- Input: State (task size, device energy, distance, etc.)
- Output: Q-values for each action (local, offload)

Key Innovations:
1. Experience Replay Buffer - stores past experiences, samples randomly
2. Target Network - separate network for stable learning targets
3. Epsilon-Greedy - balances exploration vs exploitation

================================================================================
"""

import numpy as np
import random
from collections import deque
from dataclasses import dataclass
from typing import Tuple, List, Dict
import time
import os

# For plotting (use non-interactive backend)
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt


# ==============================================================================
# PART 1: DATA STRUCTURES
# ==============================================================================

@dataclass
class Task:
    """
    Represents a computational task generated by a ground device.

    Attributes:
        data_size: Size of task data in bits (affects transmission time)
        cpu_cycles: Required CPU cycles to complete (affects processing time)
        device_id: Which device generated this task
    """
    data_size: float      # in bits
    cpu_cycles: float     # in cycles
    device_id: int


@dataclass
class GroundDevice:
    """
    Represents an IoT/ground device with limited computing capacity.

    Real-world examples: smartphones, sensors, wearables, drones

    Attributes:
        cpu_frequency: Processing speed in Hz (cycles per second)
        transmit_power: Power for wireless transmission in Watts
        energy_coefficient: Energy consumption coefficient for local computing
    """
    cpu_frequency: float = 1e9      # 1 GHz (typical IoT device)
    transmit_power: float = 1.0     # 1.0 Watts (higher transmission cost!)
    energy_coefficient: float = 1e-29  # Lower coefficient = cheaper local processing


@dataclass
class UAV:
    """
    Represents a UAV with edge computing capability.

    UAVs act as flying edge servers, providing computation services to ground devices.

    Attributes:
        cpu_frequency: Processing speed (much higher than ground devices)
        position: (x, y, altitude) coordinates
        bandwidth: Available bandwidth for communication in Hz
    """
    cpu_frequency: float = 10e9     # 10 GHz (powerful edge server)
    position: Tuple[float, float, float] = (0, 0, 100)  # x, y, altitude(m)
    bandwidth: float = 10e6         # 10 MHz bandwidth


# ==============================================================================
# PART 2: ENVIRONMENT
# ==============================================================================

class UAVOffloadingEnv:
    """
    Reinforcement Learning Environment for UAV Task Offloading.

    This environment simulates a network where:
    - Ground devices generate computational tasks
    - Each device decides: process locally OR offload to UAV
    - Goal: minimize delay and energy consumption

    STATE SPACE (5 features):
    -------------------------
    1. Task data size (normalized to [0,1])
    2. Task CPU cycles (normalized to [0,1])
    3. Device's current energy level (normalized)
    4. Distance to nearest UAV (normalized)
    5. Channel quality indicator (normalized)

    ACTION SPACE (binary):
    ----------------------
    - 0: Process locally
    - 1: Offload to nearest UAV

    REWARD:
    -------
    Reward = -(delay_weight * delay + energy_weight * energy)

    We want to MINIMIZE delay and energy, so reward is negative cost.
    Higher reward (closer to 0) means better performance!
    """

    def __init__(
        self,
        num_devices: int = 10,
        num_uavs: int = 3,
        area_size: float = 500.0,
        episode_length: int = 100,
        delay_weight: float = 0.5,
        energy_weight: float = 0.5
    ):
        """
        Initialize the UAV offloading environment.

        Args:
            num_devices: Number of ground IoT devices (default: 10)
            num_uavs: Number of UAVs providing edge computing (default: 3)
            area_size: Size of simulation area in meters (default: 500x500m)
            episode_length: Number of tasks per episode (default: 100)
            delay_weight: Weight for delay in reward function (0-1)
            energy_weight: Weight for energy in reward function (0-1)
        """
        self.num_devices = num_devices
        self.num_uavs = num_uavs
        self.area_size = area_size
        self.episode_length = episode_length
        self.delay_weight = delay_weight
        self.energy_weight = energy_weight

        # State and action dimensions
        self.state_dim = 5   # 5 features per state
        self.action_dim = 2  # Binary: 0=local, 1=offload

        # Channel parameters for wireless communication
        self.noise_power = 1e-10          # Noise power in Watts
        self.path_loss_exponent = 2.5     # Signal attenuation factor

        # Task generation parameters
        # Varied sizes create scenarios where both strategies can be optimal
        self.min_data_size = 50e3     # 50 KB minimum
        self.max_data_size = 1000e3   # 1 MB maximum
        self.min_cpu_cycles = 50e6    # 50 Mega cycles
        self.max_cpu_cycles = 1000e6  # 1000 Mega cycles

        # Initialize network topology
        self._setup_network()

        # Episode tracking
        self.current_step = 0
        self.current_task = None

    def _setup_network(self):
        """Set up the network topology with devices and UAVs."""
        # Create ground devices with varying capabilities
        # Key: Some devices have efficient local processing (low freq, low energy)
        #      Transmission is costly (high power), so small tasks favor local
        self.devices = []
        for i in range(self.num_devices):
            device = GroundDevice(
                cpu_frequency=np.random.uniform(1e9, 2e9),    # 1-2 GHz (energy efficient)
                transmit_power=np.random.uniform(1.0, 2.0),   # 1-2 W (high transmission cost!)
                energy_coefficient=np.random.uniform(5e-30, 2e-29),  # Low = efficient local
            )
            self.devices.append(device)

        # Random positions for devices (x, y coordinates)
        self.device_positions = np.random.uniform(
            0, self.area_size, size=(self.num_devices, 2)
        )

        # Create UAVs positioned across the area
        self.uavs = []
        self.uav_positions = []
        for i in range(self.num_uavs):
            uav = UAV(
                cpu_frequency=np.random.uniform(5e9, 8e9),   # 5-8 GHz
                bandwidth=np.random.uniform(5e6, 10e6),      # 5-10 MHz
            )
            self.uavs.append(uav)

            # Distribute UAVs across the area
            x = self.area_size * (i + 0.5) / self.num_uavs
            y = self.area_size / 2 + np.random.uniform(-100, 100)
            altitude = np.random.uniform(100, 150)  # 100-150m altitude
            self.uav_positions.append((x, y, altitude))

        # Device energy levels (reset each episode)
        self.device_energy = np.ones(self.num_devices) * 100  # 100 Joules

    def _generate_task(self) -> Task:
        """Generate a random computational task from a random device."""
        device_id = np.random.randint(0, self.num_devices)
        task = Task(
            data_size=np.random.uniform(self.min_data_size, self.max_data_size),
            cpu_cycles=np.random.uniform(self.min_cpu_cycles, self.max_cpu_cycles),
            device_id=device_id
        )
        return task

    def _calculate_distance_to_nearest_uav(self, device_id: int) -> Tuple[float, int]:
        """Calculate distance from device to nearest UAV."""
        device_pos = self.device_positions[device_id]
        min_distance = float('inf')
        nearest_uav = 0

        for i, uav_pos in enumerate(self.uav_positions):
            # 3D Euclidean distance
            dx = device_pos[0] - uav_pos[0]
            dy = device_pos[1] - uav_pos[1]
            dz = 0 - uav_pos[2]  # Device at ground level
            distance = np.sqrt(dx**2 + dy**2 + dz**2)

            if distance < min_distance:
                min_distance = distance
                nearest_uav = i

        return min_distance, nearest_uav

    def _calculate_channel_gain(self, distance: float) -> float:
        """
        Calculate wireless channel gain based on distance.
        Uses free-space path loss model: gain decreases with distance.
        """
        distance = max(distance, 1.0)  # Avoid division by zero
        channel_gain = 1e-4 * (distance ** (-self.path_loss_exponent))
        return channel_gain

    def _calculate_transmission_rate(self, device_id: int, uav_id: int) -> float:
        """
        Calculate achievable transmission rate using Shannon's formula.

        Rate = Bandwidth * log2(1 + SNR)
        where SNR = (transmit_power * channel_gain) / noise_power
        """
        distance, _ = self._calculate_distance_to_nearest_uav(device_id)
        channel_gain = self._calculate_channel_gain(distance)

        device = self.devices[device_id]
        uav = self.uavs[uav_id]

        # Signal-to-Noise Ratio
        snr = (device.transmit_power * channel_gain) / self.noise_power

        # Shannon capacity formula
        rate = uav.bandwidth * np.log2(1 + snr)
        return rate

    def _compute_local_cost(self, task: Task) -> Tuple[float, float]:
        """
        Compute delay and energy for LOCAL processing.

        Delay = CPU_cycles / CPU_frequency
        Energy = energy_coefficient * CPU_cycles * CPU_frequency^2

        Returns:
            Tuple of (delay in seconds, energy in Joules)
        """
        device = self.devices[task.device_id]

        # Local processing delay
        delay = task.cpu_cycles / device.cpu_frequency

        # Local energy consumption (dynamic power model)
        energy = device.energy_coefficient * task.cpu_cycles * (device.cpu_frequency ** 2)

        return delay, energy

    def _compute_offload_cost(self, task: Task) -> Tuple[float, float]:
        """
        Compute delay and energy for OFFLOADING to UAV.

        Delay = transmission_delay + UAV_processing_delay
        Energy = transmit_power * transmission_time

        Returns:
            Tuple of (delay in seconds, energy in Joules)
        """
        device = self.devices[task.device_id]
        distance, nearest_uav = self._calculate_distance_to_nearest_uav(task.device_id)
        uav = self.uavs[nearest_uav]

        # Transmission rate (bits per second)
        rate = self._calculate_transmission_rate(task.device_id, nearest_uav)

        # Transmission delay
        transmission_delay = task.data_size / rate

        # UAV processing delay
        uav_processing_delay = task.cpu_cycles / uav.cpu_frequency

        # Total delay
        total_delay = transmission_delay + uav_processing_delay

        # Energy consumed by device (only transmission)
        energy = device.transmit_power * transmission_delay

        return total_delay, energy

    def _get_state(self) -> np.ndarray:
        """
        Get the current state observation.

        State features (all normalized to [0,1] for neural network):
        1. Task data size
        2. Task CPU cycles
        3. Device energy level
        4. Distance to nearest UAV
        5. Channel quality indicator
        """
        task = self.current_task
        device_id = task.device_id

        # Normalize features to [0, 1] range
        data_size_norm = (task.data_size - self.min_data_size) / (self.max_data_size - self.min_data_size)
        cpu_cycles_norm = (task.cpu_cycles - self.min_cpu_cycles) / (self.max_cpu_cycles - self.min_cpu_cycles)
        energy_norm = self.device_energy[device_id] / 100.0

        distance, _ = self._calculate_distance_to_nearest_uav(device_id)
        max_distance = np.sqrt(2) * self.area_size + 150
        distance_norm = distance / max_distance

        channel_gain = self._calculate_channel_gain(distance)
        channel_norm = min(channel_gain / 1e-4, 1.0)

        state = np.array([
            data_size_norm,
            cpu_cycles_norm,
            energy_norm,
            distance_norm,
            channel_norm
        ], dtype=np.float32)

        return state

    def reset(self) -> np.ndarray:
        """Reset the environment for a new episode."""
        self.device_energy = np.ones(self.num_devices) * 100
        self.current_step = 0
        self.current_task = self._generate_task()
        return self._get_state()

    def step(self, action: int) -> Tuple[np.ndarray, float, bool, dict]:
        """
        Execute one step in the environment.

        Args:
            action: 0 for local processing, 1 for offloading

        Returns:
            Tuple of (next_state, reward, done, info)
        """
        task = self.current_task
        device_id = task.device_id

        # Calculate costs based on action
        if action == 0:  # Local processing
            delay, energy = self._compute_local_cost(task)
            decision = "local"
        else:  # Offload to UAV
            delay, energy = self._compute_offload_cost(task)
            decision = "offload"

        # Update device energy
        self.device_energy[device_id] = max(0, self.device_energy[device_id] - energy)

        # Calculate reward (negative cost)
        delay_normalized = delay / 1.0
        energy_normalized = energy / 1.0
        reward = -(self.delay_weight * delay_normalized + self.energy_weight * energy_normalized)

        # Penalty for running out of energy
        if self.device_energy[device_id] <= 0:
            reward -= 10.0

        # Move to next step
        self.current_step += 1
        done = self.current_step >= self.episode_length

        # Generate next task
        if not done:
            self.current_task = self._generate_task()
            next_state = self._get_state()
        else:
            next_state = np.zeros(self.state_dim, dtype=np.float32)

        info = {
            'delay': delay,
            'energy': energy,
            'decision': decision,
            'device_id': device_id
        }

        return next_state, reward, done, info


# ==============================================================================
# PART 3: REPLAY BUFFER
# ==============================================================================

class ReplayBuffer:
    """
    Experience Replay Buffer for DQN.

    WHY USE REPLAY BUFFER?
    ----------------------
    1. Breaks correlation between consecutive experiences
    2. Allows reuse of past experiences multiple times
    3. Improves sample efficiency and training stability

    Each experience is a tuple: (state, action, reward, next_state, done)
    """

    def __init__(self, capacity: int = 10000):
        self.buffer = deque(maxlen=capacity)

    def push(self, state, action, reward, next_state, done):
        """Add an experience to the buffer."""
        self.buffer.append((state, action, reward, next_state, done))

    def sample(self, batch_size: int):
        """Randomly sample a batch of experiences."""
        batch = random.sample(self.buffer, batch_size)

        states = np.array([exp[0] for exp in batch])
        actions = np.array([exp[1] for exp in batch])
        rewards = np.array([exp[2] for exp in batch])
        next_states = np.array([exp[3] for exp in batch])
        dones = np.array([exp[4] for exp in batch])

        return states, actions, rewards, next_states, dones

    def __len__(self):
        return len(self.buffer)


# ==============================================================================
# PART 4: NEURAL NETWORK (FROM SCRATCH!)
# ==============================================================================

class NeuralNetwork:
    """
    Simple Neural Network implemented from scratch.

    No PyTorch or TensorFlow needed! This is for educational purposes.

    Architecture: Input → Hidden1(ReLU) → Hidden2(ReLU) → Output(Linear)

    For production use, you'd want to use PyTorch/TensorFlow for:
    - GPU acceleration
    - Automatic differentiation
    - More optimizers
    """

    def __init__(self, input_dim: int, hidden_dims: List[int], output_dim: int,
                 learning_rate: float = 0.001):
        self.learning_rate = learning_rate
        self.layers = []
        self.biases = []

        # Build layers with Xavier initialization
        dims = [input_dim] + hidden_dims + [output_dim]
        for i in range(len(dims) - 1):
            scale = np.sqrt(2.0 / dims[i])  # Xavier init
            W = np.random.randn(dims[i], dims[i+1]) * scale
            b = np.zeros((1, dims[i+1]))
            self.layers.append(W)
            self.biases.append(b)

    def relu(self, x):
        """ReLU activation: max(0, x)"""
        return np.maximum(0, x)

    def relu_derivative(self, x):
        """Derivative of ReLU"""
        return (x > 0).astype(float)

    def forward(self, x):
        """Forward pass through the network."""
        activations = [x]

        for i, (W, b) in enumerate(zip(self.layers, self.biases)):
            x = np.dot(x, W) + b
            if i < len(self.layers) - 1:  # ReLU for hidden layers
                x = self.relu(x)
            activations.append(x)

        return x, activations

    def predict(self, x):
        """Get Q-values for given states."""
        output, _ = self.forward(x)
        return output

    def train_step(self, states, actions, targets):
        """Perform one training step with backpropagation."""
        batch_size = states.shape[0]

        # Forward pass
        output, activations = self.forward(states)

        # Calculate loss (MSE for taken actions only)
        target_q = output.copy()
        loss = 0.0
        for i in range(batch_size):
            target_q[i, actions[i]] = targets[i]
            loss += (output[i, actions[i]] - targets[i]) ** 2
        loss /= batch_size

        # Backward pass
        dL_dout = 2 * (output - target_q) / batch_size
        delta = dL_dout

        gradients_W = []
        gradients_b = []

        for i in range(len(self.layers) - 1, -1, -1):
            dW = np.dot(activations[i].T, delta)
            db = np.sum(delta, axis=0, keepdims=True)
            gradients_W.insert(0, dW)
            gradients_b.insert(0, db)

            if i > 0:
                delta = np.dot(delta, self.layers[i].T)
                delta = delta * self.relu_derivative(activations[i])

        # Update weights (gradient descent)
        for i in range(len(self.layers)):
            self.layers[i] -= self.learning_rate * gradients_W[i]
            self.biases[i] -= self.learning_rate * gradients_b[i]

        return loss

    def copy_weights_from(self, other):
        """Copy weights from another network."""
        for i in range(len(self.layers)):
            self.layers[i] = other.layers[i].copy()
            self.biases[i] = other.biases[i].copy()


# ==============================================================================
# PART 5: DQN AGENT
# ==============================================================================

class DQNAgent:
    """
    Deep Q-Network Agent for Task Offloading.

    The agent learns to make binary offloading decisions:
    - Action 0: Process task locally
    - Action 1: Offload task to UAV

    KEY COMPONENTS:
    ---------------
    1. Q-Network: Neural network that predicts Q-values
    2. Target Network: Stable copy for computing targets
    3. Replay Buffer: Stores experiences for training
    4. Epsilon-Greedy: Exploration strategy
    """

    def __init__(
        self,
        state_dim: int,
        action_dim: int = 2,
        hidden_dims: List[int] = [64, 64],
        learning_rate: float = 0.001,
        gamma: float = 0.99,
        epsilon_start: float = 1.0,
        epsilon_end: float = 0.01,
        epsilon_decay: float = 0.995,
        buffer_size: int = 10000,
        batch_size: int = 64,
        target_update_freq: int = 10
    ):
        """
        Initialize the DQN agent.

        Args:
            state_dim: Size of state space (5 for our environment)
            action_dim: Number of actions (2: local or offload)
            hidden_dims: Sizes of hidden layers
            learning_rate: How fast to update weights
            gamma: Discount factor for future rewards (0.99 = value future)
            epsilon_start: Initial exploration rate (1.0 = 100% random)
            epsilon_end: Final exploration rate (0.01 = 1% random)
            epsilon_decay: How fast epsilon decreases each episode
            buffer_size: Replay buffer capacity
            batch_size: Samples per training step
            target_update_freq: Episodes between target network updates
        """
        self.state_dim = state_dim
        self.action_dim = action_dim
        self.gamma = gamma
        self.batch_size = batch_size
        self.target_update_freq = target_update_freq

        # Epsilon for exploration
        self.epsilon = epsilon_start
        self.epsilon_end = epsilon_end
        self.epsilon_decay = epsilon_decay

        # Q-Network (gets updated every step)
        self.q_network = NeuralNetwork(state_dim, hidden_dims, action_dim, learning_rate)

        # Target Network (updated less frequently for stability)
        self.target_network = NeuralNetwork(state_dim, hidden_dims, action_dim, learning_rate)
        self.target_network.copy_weights_from(self.q_network)

        # Experience replay
        self.replay_buffer = ReplayBuffer(buffer_size)

        self.episode_count = 0

    def select_action(self, state: np.ndarray, training: bool = True) -> int:
        """
        Select action using epsilon-greedy policy.

        EPSILON-GREEDY:
        - With probability epsilon: random action (EXPLORE)
        - With probability 1-epsilon: best action (EXPLOIT)

        During training, we start with high exploration and gradually exploit more.
        """
        if training and random.random() < self.epsilon:
            return random.randint(0, self.action_dim - 1)
        else:
            state = state.reshape(1, -1)
            q_values = self.q_network.predict(state)
            return np.argmax(q_values[0])

    def store_experience(self, state, action, reward, next_state, done):
        """Store experience in replay buffer."""
        self.replay_buffer.push(state, action, reward, next_state, done)

    def train(self) -> float:
        """
        Train the agent using experiences from replay buffer.

        DQN UPDATE RULE:
        ----------------
        For each experience (s, a, r, s', done):

        if done:
            target = r
        else:
            target = r + gamma * max_a' Q_target(s', a')

        Then minimize: (Q(s, a) - target)^2
        """
        if len(self.replay_buffer) < self.batch_size:
            return 0.0

        # Sample batch
        states, actions, rewards, next_states, dones = self.replay_buffer.sample(self.batch_size)

        # Compute targets using target network
        next_q_values = self.target_network.predict(next_states)
        max_next_q = np.max(next_q_values, axis=1)
        targets = rewards + (1 - dones) * self.gamma * max_next_q

        # Update Q-network
        loss = self.q_network.train_step(states, actions, targets)

        return loss

    def decay_epsilon(self):
        """Decay exploration rate after each episode."""
        self.epsilon = max(self.epsilon_end, self.epsilon * self.epsilon_decay)
        self.episode_count += 1

        # Update target network periodically
        if self.episode_count % self.target_update_freq == 0:
            self.target_network.copy_weights_from(self.q_network)


# ==============================================================================
# PART 6: BASELINE POLICIES
# ==============================================================================

class AllLocalBaseline:
    """Always processes tasks locally (never offloads)."""
    def select_action(self, state, training=True):
        return 0


class AllOffloadBaseline:
    """Always offloads tasks to UAV (never processes locally)."""
    def select_action(self, state, training=True):
        return 1


class RandomBaseline:
    """Randomly chooses between local and offload."""
    def select_action(self, state, training=True):
        return random.randint(0, 1)


# ==============================================================================
# PART 7: TRAINING FUNCTIONS
# ==============================================================================

def train_dqn(env, agent, num_episodes=500, print_every=50):
    """
    Train the DQN agent.

    Args:
        env: The UAV offloading environment
        agent: The DQN agent
        num_episodes: Number of training episodes
        print_every: Print progress every N episodes

    Returns:
        Training history dictionary
    """
    history = {
        'episode_rewards': [],
        'episode_delays': [],
        'episode_energies': [],
        'losses': [],
        'epsilons': []
    }

    print("=" * 60)
    print("TRAINING DQN AGENT")
    print("=" * 60)
    print(f"Episodes: {num_episodes}")
    print(f"State dim: {env.state_dim}, Action dim: {env.action_dim}")
    print("=" * 60)

    for episode in range(num_episodes):
        state = env.reset()
        episode_reward = 0
        episode_delay = 0
        episode_energy = 0
        episode_losses = []

        done = False
        while not done:
            # Select and execute action
            action = agent.select_action(state, training=True)
            next_state, reward, done, info = env.step(action)

            # Store and train
            agent.store_experience(state, action, reward, next_state, done)
            loss = agent.train()
            if loss > 0:
                episode_losses.append(loss)

            # Track metrics
            episode_reward += reward
            episode_delay += info['delay']
            episode_energy += info['energy']

            state = next_state

        # End of episode
        agent.decay_epsilon()

        # Store history
        history['episode_rewards'].append(episode_reward)
        history['episode_delays'].append(episode_delay)
        history['episode_energies'].append(episode_energy)
        history['losses'].append(np.mean(episode_losses) if episode_losses else 0)
        history['epsilons'].append(agent.epsilon)

        # Print progress
        if (episode + 1) % print_every == 0:
            avg_reward = np.mean(history['episode_rewards'][-print_every:])
            avg_delay = np.mean(history['episode_delays'][-print_every:])
            print(f"Episode {episode+1}/{num_episodes} | "
                  f"Avg Reward: {avg_reward:.2f} | "
                  f"Avg Delay: {avg_delay*1000:.1f}ms | "
                  f"Epsilon: {agent.epsilon:.3f}")

    return history


def evaluate_policy(env, policy, num_episodes=100):
    """Evaluate a policy over multiple episodes."""
    total_rewards = []
    total_delays = []
    total_energies = []
    local_count = 0
    offload_count = 0

    for _ in range(num_episodes):
        state = env.reset()
        episode_reward = 0
        episode_delay = 0
        episode_energy = 0

        done = False
        while not done:
            action = policy.select_action(state, training=False)
            next_state, reward, done, info = env.step(action)

            episode_reward += reward
            episode_delay += info['delay']
            episode_energy += info['energy']

            if action == 0:
                local_count += 1
            else:
                offload_count += 1

            state = next_state

        total_rewards.append(episode_reward)
        total_delays.append(episode_delay)
        total_energies.append(episode_energy)

    return {
        'avg_reward': np.mean(total_rewards),
        'std_reward': np.std(total_rewards),
        'avg_delay': np.mean(total_delays),
        'std_delay': np.std(total_delays),
        'avg_energy': np.mean(total_energies),
        'std_energy': np.std(total_energies),
        'local_ratio': local_count / (local_count + offload_count),
        'offload_ratio': offload_count / (local_count + offload_count)
    }


def compare_policies(env, dqn_agent, num_episodes=100):
    """Compare DQN with baseline policies."""
    print("\n" + "=" * 60)
    print("COMPARING POLICIES")
    print("=" * 60)

    policies = {
        'DQN': dqn_agent,
        'All Local': AllLocalBaseline(),
        'All Offload': AllOffloadBaseline(),
        'Random': RandomBaseline()
    }

    results = {}
    for name, policy in policies.items():
        print(f"Evaluating {name}...")
        results[name] = evaluate_policy(env, policy, num_episodes)

    # Print comparison table
    print("\n" + "=" * 80)
    print(f"{'Policy':<15} {'Avg Reward':<15} {'Avg Delay (ms)':<18} {'Avg Energy (mJ)':<18} {'Local %':<10}")
    print("-" * 80)

    for name, res in results.items():
        print(f"{name:<15} {res['avg_reward']:<15.2f} {res['avg_delay']*1000:<18.2f} "
              f"{res['avg_energy']*1000:<18.2f} {res['local_ratio']*100:<10.1f}")

    print("=" * 80)

    # Print improvements
    print("\nDQN IMPROVEMENT OVER BASELINES:")
    dqn_reward = results['DQN']['avg_reward']
    for name in ['All Local', 'All Offload', 'Random']:
        baseline_reward = results[name]['avg_reward']
        improvement = ((dqn_reward - baseline_reward) / abs(baseline_reward)) * 100
        print(f"  vs {name}: {improvement:+.1f}%")

    return results


# ==============================================================================
# PART 8: VISUALIZATION
# ==============================================================================

def plot_results(history, results, save_dir="./results"):
    """Generate and save all plots."""
    os.makedirs(save_dir, exist_ok=True)

    # Plot 1: Training History
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    fig.suptitle('DQN Training Progress', fontsize=16, fontweight='bold')

    episodes = range(1, len(history['episode_rewards']) + 1)

    # Smoothing function
    def smooth(data, window=20):
        smoothed = []
        for i in range(len(data)):
            start = max(0, i - window // 2)
            end = min(len(data), i + window // 2)
            smoothed.append(np.mean(data[start:end]))
        return smoothed

    # Rewards
    axes[0, 0].plot(episodes, history['episode_rewards'], alpha=0.3, color='blue')
    axes[0, 0].plot(episodes, smooth(history['episode_rewards']), color='blue', linewidth=2)
    axes[0, 0].set_xlabel('Episode')
    axes[0, 0].set_ylabel('Reward')
    axes[0, 0].set_title('Episode Rewards (Higher is Better)')
    axes[0, 0].grid(True, alpha=0.3)

    # Delays
    delays_ms = [d * 1000 for d in history['episode_delays']]
    axes[0, 1].plot(episodes, delays_ms, alpha=0.3, color='red')
    axes[0, 1].plot(episodes, smooth(delays_ms), color='red', linewidth=2)
    axes[0, 1].set_xlabel('Episode')
    axes[0, 1].set_ylabel('Delay (ms)')
    axes[0, 1].set_title('Episode Delays (Lower is Better)')
    axes[0, 1].grid(True, alpha=0.3)

    # Loss
    axes[1, 0].plot(episodes, history['losses'], alpha=0.3, color='green')
    axes[1, 0].plot(episodes, smooth(history['losses']), color='green', linewidth=2)
    axes[1, 0].set_xlabel('Episode')
    axes[1, 0].set_ylabel('Loss')
    axes[1, 0].set_title('Training Loss')
    axes[1, 0].grid(True, alpha=0.3)

    # Epsilon
    axes[1, 1].plot(episodes, history['epsilons'], color='purple', linewidth=2)
    axes[1, 1].set_xlabel('Episode')
    axes[1, 1].set_ylabel('Epsilon')
    axes[1, 1].set_title('Exploration Rate Decay')
    axes[1, 1].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(f"{save_dir}/training_history.png", dpi=150)
    plt.close()

    # Plot 2: Policy Comparison
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    fig.suptitle('Policy Comparison', fontsize=16, fontweight='bold')

    policies = list(results.keys())
    x = np.arange(len(policies))
    colors = ['#2ecc71', '#e74c3c', '#3498db', '#9b59b6']

    # Rewards
    rewards = [results[p]['avg_reward'] for p in policies]
    axes[0].bar(x, rewards, color=colors)
    axes[0].set_xticks(x)
    axes[0].set_xticklabels(policies)
    axes[0].set_ylabel('Average Reward')
    axes[0].set_title('Reward (Higher is Better)')
    axes[0].grid(True, alpha=0.3, axis='y')

    # Delays
    delays = [results[p]['avg_delay'] * 1000 for p in policies]
    axes[1].bar(x, delays, color=colors)
    axes[1].set_xticks(x)
    axes[1].set_xticklabels(policies)
    axes[1].set_ylabel('Average Delay (ms)')
    axes[1].set_title('Delay (Lower is Better)')
    axes[1].grid(True, alpha=0.3, axis='y')

    # Energy
    energies = [results[p]['avg_energy'] * 1000 for p in policies]
    axes[2].bar(x, energies, color=colors)
    axes[2].set_xticks(x)
    axes[2].set_xticklabels(policies)
    axes[2].set_ylabel('Average Energy (mJ)')
    axes[2].set_title('Energy (Lower is Better)')
    axes[2].grid(True, alpha=0.3, axis='y')

    plt.tight_layout()
    plt.savefig(f"{save_dir}/policy_comparison.png", dpi=150)
    plt.close()

    # Plot 3: Offload Ratio
    fig, ax = plt.subplots(figsize=(10, 6))

    local_ratios = [results[p]['local_ratio'] * 100 for p in policies]
    offload_ratios = [results[p]['offload_ratio'] * 100 for p in policies]

    ax.bar(x, local_ratios, label='Local', color='#3498db')
    ax.bar(x, offload_ratios, bottom=local_ratios, label='Offload', color='#e74c3c')
    ax.set_xticks(x)
    ax.set_xticklabels(policies)
    ax.set_ylabel('Percentage (%)')
    ax.set_title('Task Processing Distribution')
    ax.legend()
    ax.set_ylim(0, 100)

    plt.tight_layout()
    plt.savefig(f"{save_dir}/offload_ratio.png", dpi=150)
    plt.close()

    print(f"\nPlots saved to {save_dir}/")


# ==============================================================================
# PART 9: MAIN FUNCTION
# ==============================================================================

def main():
    """Main function to run the complete experiment."""

    print("""
    ╔═══════════════════════════════════════════════════════════════════════╗
    ║                                                                       ║
    ║   DQN FOR UAV TASK OFFLOADING - COMPLETE TUTORIAL                     ║
    ║                                                                       ║
    ║   This program demonstrates Deep Q-Network for task offloading        ║
    ║   in UAV-assisted edge computing networks.                            ║
    ║                                                                       ║
    ╚═══════════════════════════════════════════════════════════════════════╝
    """)

    # Configuration
    NUM_DEVICES = 10
    NUM_UAVS = 3
    TRAIN_EPISODES = 500
    EVAL_EPISODES = 100

    # Reward weights - adjust these to prioritize delay vs energy
    DELAY_WEIGHT = 0.3   # Lower weight for delay
    ENERGY_WEIGHT = 0.7  # Higher weight for energy (prioritize energy saving!)

    print("CONFIGURATION:")
    print(f"  Ground Devices: {NUM_DEVICES}")
    print(f"  UAVs: {NUM_UAVS}")
    print(f"  Training Episodes: {TRAIN_EPISODES}")
    print(f"  Evaluation Episodes: {EVAL_EPISODES}")
    print(f"  Delay Weight: {DELAY_WEIGHT}")
    print(f"  Energy Weight: {ENERGY_WEIGHT} (prioritizing energy!)")

    # Create environment
    print("\n[1/4] Creating environment...")
    env = UAVOffloadingEnv(
        num_devices=NUM_DEVICES,
        num_uavs=NUM_UAVS,
        episode_length=100,
        delay_weight=DELAY_WEIGHT,
        energy_weight=ENERGY_WEIGHT
    )

    # Create DQN agent
    print("[2/4] Creating DQN agent...")
    agent = DQNAgent(
        state_dim=env.state_dim,
        action_dim=env.action_dim,
        hidden_dims=[64, 64],
        learning_rate=0.001,
        gamma=0.99,
        epsilon_start=1.0,
        epsilon_end=0.01,
        epsilon_decay=0.995,
        buffer_size=10000,
        batch_size=64,
        target_update_freq=10
    )

    # Train
    print("[3/4] Training DQN agent...")
    start_time = time.time()
    history = train_dqn(env, agent, TRAIN_EPISODES, print_every=50)
    print(f"\nTraining completed in {time.time() - start_time:.1f} seconds")

    # Evaluate and compare
    print("\n[4/4] Evaluating policies...")
    results = compare_policies(env, agent, EVAL_EPISODES)

    # Generate plots
    plot_results(history, results)

    # Final summary
    print("\n" + "=" * 60)
    print("EXPERIMENT COMPLETE!")
    print("=" * 60)
    print(f"""
    DQN learned to make intelligent offloading decisions!

    Key Results:
    - DQN Reward: {results['DQN']['avg_reward']:.2f}
    - DQN Delay: {results['DQN']['avg_delay']*1000:.1f} ms
    - DQN Offload Ratio: {results['DQN']['offload_ratio']*100:.1f}%

    Improvements over baselines:
    - vs All Local: {((results['DQN']['avg_reward'] - results['All Local']['avg_reward']) / abs(results['All Local']['avg_reward'])) * 100:+.1f}%
    - vs All Offload: {((results['DQN']['avg_reward'] - results['All Offload']['avg_reward']) / abs(results['All Offload']['avg_reward'])) * 100:+.1f}%
    - vs Random: {((results['DQN']['avg_reward'] - results['Random']['avg_reward']) / abs(results['Random']['avg_reward'])) * 100:+.1f}%

    Check ./results/ folder for visualization plots!
    """)

    return agent, history, results


# ==============================================================================
# RUN
# ==============================================================================

if __name__ == "__main__":
    agent, history, results = main()
