"""
UAV Task Offloading Environment
===============================

This module simulates an edge-enabled UAV network where:
- Ground devices (IoT devices) generate computational tasks
- Each device can either process locally OR offload to a UAV
- The goal is to minimize total delay + energy consumption

Key Concepts:
-------------
1. LOCAL PROCESSING: Device processes task itself (slower, uses device energy)
2. OFFLOADING: Send task to UAV (transmission delay + UAV processing, saves device energy)

The environment follows OpenAI Gym-like interface for compatibility with RL algorithms.
"""

import numpy as np
from dataclasses import dataclass
from typing import Tuple, List


@dataclass
class Task:
    """
    Represents a computational task generated by a ground device.

    Attributes:
        data_size: Size of task data in bits (affects transmission time)
        cpu_cycles: Required CPU cycles to complete (affects processing time)
        device_id: Which device generated this task
    """
    data_size: float      # in bits
    cpu_cycles: float     # in cycles
    device_id: int


@dataclass
class GroundDevice:
    """
    Represents an IoT/ground device with limited computing capacity.

    Attributes:
        cpu_frequency: Processing speed in Hz (cycles per second)
        transmit_power: Power for wireless transmission in Watts
        energy_coefficient: Energy consumption coefficient for local computing
    """
    cpu_frequency: float = 1e9      # 1 GHz (typical IoT device)
    transmit_power: float = 0.5     # 0.5 Watts
    energy_coefficient: float = 1e-28  # Energy per CPU cycle coefficient (reduced for balance)


@dataclass
class UAV:
    """
    Represents a UAV with edge computing capability.

    Attributes:
        cpu_frequency: Processing speed (much higher than ground devices)
        position: (x, y, altitude) coordinates
        bandwidth: Available bandwidth for communication in Hz
    """
    cpu_frequency: float = 10e9     # 10 GHz (powerful edge server)
    position: Tuple[float, float, float] = (0, 0, 100)  # x, y, altitude(m)
    bandwidth: float = 10e6         # 10 MHz bandwidth


class UAVOffloadingEnv:
    """
    Reinforcement Learning Environment for UAV Task Offloading.

    STATE SPACE:
    ------------
    For each device, we observe:
    - Task data size (normalized)
    - Task CPU cycles (normalized)
    - Device's current energy level
    - Distance to nearest UAV
    - Channel quality indicator

    ACTION SPACE:
    -------------
    Binary decision for each device:
    - 0: Process locally
    - 1: Offload to nearest UAV

    REWARD:
    -------
    Negative of (weighted delay + weighted energy consumption)
    We want to MINIMIZE delay and energy, so reward is negative cost.
    """

    def __init__(
        self,
        num_devices: int = 10,
        num_uavs: int = 3,
        area_size: float = 500.0,  # 500m x 500m area
        episode_length: int = 100,  # tasks per episode
        delay_weight: float = 0.5,
        energy_weight: float = 0.5
    ):
        """
        Initialize the UAV offloading environment.

        Args:
            num_devices: Number of ground IoT devices
            num_uavs: Number of UAVs providing edge computing
            area_size: Size of the simulation area in meters
            episode_length: Number of tasks per episode
            delay_weight: Weight for delay in reward (0-1)
            energy_weight: Weight for energy in reward (0-1)
        """
        self.num_devices = num_devices
        self.num_uavs = num_uavs
        self.area_size = area_size
        self.episode_length = episode_length
        self.delay_weight = delay_weight
        self.energy_weight = energy_weight

        # State and action dimensions
        self.state_dim = 5  # Features per task (see _get_state)
        self.action_dim = 2  # Binary: 0=local, 1=offload

        # Channel parameters (for wireless communication)
        self.noise_power = 1e-10  # Noise power in Watts
        self.path_loss_exponent = 2.5  # For signal attenuation

        # Task generation parameters
        # Note: We use varied task sizes to create scenarios where:
        # - Small tasks: local processing might be better (low transmission overhead)
        # - Large tasks: offloading might be better (leverage UAV power)
        self.min_data_size = 50e3    # 50 KB minimum (smaller tasks favor local)
        self.max_data_size = 1000e3  # 1 MB maximum (larger tasks favor offload)
        self.min_cpu_cycles = 50e6   # 50 Mega cycles minimum
        self.max_cpu_cycles = 1000e6 # 1000 Mega cycles maximum

        # Initialize devices and UAVs
        self._setup_network()

        # Episode tracking
        self.current_step = 0
        self.current_task = None

    def _setup_network(self):
        """Set up the network topology with devices and UAVs."""
        # Create ground devices with varying capabilities
        # Some devices are more powerful, making local processing viable
        self.devices = []
        for i in range(self.num_devices):
            device = GroundDevice(
                cpu_frequency=np.random.uniform(1.5e9, 4e9),   # 1.5-4 GHz (powerful devices)
                transmit_power=np.random.uniform(0.5, 1.5),    # 0.5-1.5 W (higher transmission cost)
            )
            self.devices.append(device)

        # Random positions for devices (x, y coordinates)
        self.device_positions = np.random.uniform(
            0, self.area_size, size=(self.num_devices, 2)
        )

        # Create UAVs positioned strategically across the area
        self.uavs = []
        self.uav_positions = []
        for i in range(self.num_uavs):
            uav = UAV(
                cpu_frequency=np.random.uniform(5e9, 8e9),  # 5-8 GHz (slightly less powerful)
                bandwidth=np.random.uniform(5e6, 10e6),     # 5-10 MHz (variable bandwidth)
            )
            self.uavs.append(uav)

            # Distribute UAVs across the area (some far from devices)
            x = self.area_size * (i + 0.5) / self.num_uavs
            y = self.area_size / 2 + np.random.uniform(-100, 100)
            altitude = np.random.uniform(100, 150)  # 100-150m altitude (higher = more delay)
            self.uav_positions.append((x, y, altitude))

        # Device energy levels (will be reset each episode)
        self.device_energy = np.ones(self.num_devices) * 100  # 100 Joules initial

    def _generate_task(self) -> Task:
        """Generate a random computational task from a random device."""
        device_id = np.random.randint(0, self.num_devices)
        task = Task(
            data_size=np.random.uniform(self.min_data_size, self.max_data_size),
            cpu_cycles=np.random.uniform(self.min_cpu_cycles, self.max_cpu_cycles),
            device_id=device_id
        )
        return task

    def _calculate_distance_to_nearest_uav(self, device_id: int) -> Tuple[float, int]:
        """
        Calculate distance from device to nearest UAV.

        Returns:
            Tuple of (distance, uav_index)
        """
        device_pos = self.device_positions[device_id]
        min_distance = float('inf')
        nearest_uav = 0

        for i, uav_pos in enumerate(self.uav_positions):
            # 3D distance (device is at ground level, z=0)
            dx = device_pos[0] - uav_pos[0]
            dy = device_pos[1] - uav_pos[1]
            dz = 0 - uav_pos[2]  # Device at ground level
            distance = np.sqrt(dx**2 + dy**2 + dz**2)

            if distance < min_distance:
                min_distance = distance
                nearest_uav = i

        return min_distance, nearest_uav

    def _calculate_channel_gain(self, distance: float) -> float:
        """
        Calculate wireless channel gain based on distance.
        Uses free-space path loss model.

        Args:
            distance: Distance between device and UAV in meters

        Returns:
            Channel gain (higher is better)
        """
        # Avoid division by zero
        distance = max(distance, 1.0)
        # Path loss model: gain decreases with distance
        channel_gain = 1e-4 * (distance ** (-self.path_loss_exponent))
        return channel_gain

    def _calculate_transmission_rate(self, device_id: int, uav_id: int) -> float:
        """
        Calculate achievable transmission rate using Shannon's formula.

        Rate = Bandwidth * log2(1 + SNR)
        where SNR = (transmit_power * channel_gain) / noise_power
        """
        distance, _ = self._calculate_distance_to_nearest_uav(device_id)
        channel_gain = self._calculate_channel_gain(distance)

        device = self.devices[device_id]
        uav = self.uavs[uav_id]

        # Signal-to-Noise Ratio
        snr = (device.transmit_power * channel_gain) / self.noise_power

        # Shannon capacity
        rate = uav.bandwidth * np.log2(1 + snr)
        return rate

    def _compute_local_cost(self, task: Task) -> Tuple[float, float]:
        """
        Compute delay and energy for LOCAL processing.

        Delay = CPU_cycles / CPU_frequency
        Energy = energy_coefficient * CPU_cycles * CPU_frequency^2

        Returns:
            Tuple of (delay in seconds, energy in Joules)
        """
        device = self.devices[task.device_id]

        # Local processing delay
        delay = task.cpu_cycles / device.cpu_frequency

        # Local energy consumption (dynamic power model)
        energy = device.energy_coefficient * task.cpu_cycles * (device.cpu_frequency ** 2)

        return delay, energy

    def _compute_offload_cost(self, task: Task) -> Tuple[float, float]:
        """
        Compute delay and energy for OFFLOADING to UAV.

        Delay = transmission_delay + UAV_processing_delay
        Energy = transmit_power * transmission_time (device only transmits)

        Note: We ignore UAV energy as it's not a constraint for the device.

        Returns:
            Tuple of (delay in seconds, energy in Joules)
        """
        device = self.devices[task.device_id]
        distance, nearest_uav = self._calculate_distance_to_nearest_uav(task.device_id)
        uav = self.uavs[nearest_uav]

        # Transmission rate
        rate = self._calculate_transmission_rate(task.device_id, nearest_uav)

        # Transmission delay (upload task data)
        transmission_delay = task.data_size / rate

        # UAV processing delay
        uav_processing_delay = task.cpu_cycles / uav.cpu_frequency

        # Total delay (we ignore download delay assuming results are small)
        total_delay = transmission_delay + uav_processing_delay

        # Energy consumed by device (only transmission energy)
        energy = device.transmit_power * transmission_delay

        return total_delay, energy

    def _get_state(self) -> np.ndarray:
        """
        Get the current state observation.

        State features (normalized to [0,1] range for neural network):
        1. Task data size (normalized)
        2. Task CPU cycles (normalized)
        3. Device energy level (normalized)
        4. Distance to nearest UAV (normalized)
        5. Channel quality indicator (normalized)
        """
        task = self.current_task
        device_id = task.device_id

        # Normalize features to [0, 1] range
        data_size_norm = (task.data_size - self.min_data_size) / (self.max_data_size - self.min_data_size)
        cpu_cycles_norm = (task.cpu_cycles - self.min_cpu_cycles) / (self.max_cpu_cycles - self.min_cpu_cycles)
        energy_norm = self.device_energy[device_id] / 100.0  # Normalized by initial energy

        distance, nearest_uav = self._calculate_distance_to_nearest_uav(device_id)
        max_distance = np.sqrt(2) * self.area_size + 120  # Maximum possible distance
        distance_norm = distance / max_distance

        # Channel quality (inverse of distance, normalized)
        channel_gain = self._calculate_channel_gain(distance)
        channel_norm = min(channel_gain / 1e-4, 1.0)  # Normalize

        state = np.array([
            data_size_norm,
            cpu_cycles_norm,
            energy_norm,
            distance_norm,
            channel_norm
        ], dtype=np.float32)

        return state

    def reset(self) -> np.ndarray:
        """
        Reset the environment for a new episode.

        Returns:
            Initial state observation
        """
        # Reset energy levels
        self.device_energy = np.ones(self.num_devices) * 100

        # Reset step counter
        self.current_step = 0

        # Generate first task
        self.current_task = self._generate_task()

        return self._get_state()

    def step(self, action: int) -> Tuple[np.ndarray, float, bool, dict]:
        """
        Execute one step in the environment.

        Args:
            action: 0 for local processing, 1 for offloading

        Returns:
            Tuple of (next_state, reward, done, info)
        """
        task = self.current_task
        device_id = task.device_id

        # Calculate costs based on action
        if action == 0:  # Local processing
            delay, energy = self._compute_local_cost(task)
            decision = "local"
        else:  # Offload to UAV
            delay, energy = self._compute_offload_cost(task)
            decision = "offload"

        # Update device energy
        self.device_energy[device_id] = max(0, self.device_energy[device_id] - energy)

        # Calculate reward (negative cost - we want to minimize)
        # Normalize delay and energy to similar scales
        delay_normalized = delay / 1.0  # Typical delay around 0.1-1 seconds
        energy_normalized = energy / 1.0  # Typical energy around 0.01-1 Joules

        reward = -(self.delay_weight * delay_normalized + self.energy_weight * energy_normalized)

        # Penalty for running out of energy
        if self.device_energy[device_id] <= 0:
            reward -= 10.0

        # Move to next step
        self.current_step += 1
        done = self.current_step >= self.episode_length

        # Generate next task (if not done)
        if not done:
            self.current_task = self._generate_task()
            next_state = self._get_state()
        else:
            next_state = np.zeros(self.state_dim, dtype=np.float32)

        info = {
            'delay': delay,
            'energy': energy,
            'decision': decision,
            'device_id': device_id,
            'remaining_energy': self.device_energy[device_id]
        }

        return next_state, reward, done, info

    def compute_all_local_cost(self, task: Task) -> Tuple[float, float]:
        """Utility method to get local cost for a task."""
        return self._compute_local_cost(task)

    def compute_all_offload_cost(self, task: Task) -> Tuple[float, float]:
        """Utility method to get offload cost for a task."""
        return self._compute_offload_cost(task)


# Example usage and testing
if __name__ == "__main__":
    # Create environment
    env = UAVOffloadingEnv(num_devices=10, num_uavs=3)

    # Test reset
    state = env.reset()
    print(f"Initial state shape: {state.shape}")
    print(f"Initial state: {state}")

    # Test a few steps with random actions
    total_reward = 0
    for i in range(5):
        action = np.random.randint(0, 2)
        next_state, reward, done, info = env.step(action)
        total_reward += reward
        print(f"\nStep {i+1}:")
        print(f"  Action: {info['decision']}")
        print(f"  Delay: {info['delay']*1000:.2f} ms")
        print(f"  Energy: {info['energy']*1000:.4f} mJ")
        print(f"  Reward: {reward:.4f}")

    print(f"\nTotal reward after 5 steps: {total_reward:.4f}")
